version: '3.9'
services:
  mongodb: 
    restart: always
    image: mongo:5.0.8
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  api:
    restart: always
    container_name: api
    build:
      context: .
    ports:
      - 5000:5000
    depends_on: 
      - mongodb