name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login
      run: |
          docker login --username  ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      run: |
        echo "Building version ${{ github.run_id }}"
        docker build -t ${{ secrets.DOCKER_REGISTRY }}/restapi-flask:${{ github.run_id }} .
          
